name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        # Assuming Docker is already installed on the GitHub Actions runner
        run: echo "Docker is already installed"

      - name: Build and push Docker image to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/almccutc/texas-trees:latest .
          docker push ghcr.io/almccutc/texas-trees:latest

      - name: SSH into EC2 and pull Docker image
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -o StrictHostKeyChecking=no ec2-user@3.135.164.135 "docker pull ghcr.io/almccutc/texas-trees:latest"

      - name: SSH into EC2 and restart Docker container
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -o StrictHostKeyChecking=no ec2-user@3.135.164.135 "docker stop texas-trees || true"
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -o StrictHostKeyChecking=no ec2-user@3.135.164.135 "docker rm texas-trees || true"
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -o StrictHostKeyChecking=no ec2-user@3.135.164.135 "docker run -d -p 80:5000 ghcr.io/almccutc/texas-trees:latest"
