name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "$AWS_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          eval "$(ssh-agent -s)"
          ssh-add key.pem
          ssh-keyscan -H $HOSTNAME >> ~/.ssh/known_hosts

      - name: Pull Docker image on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME "docker pull ghcr.io/almccutc/texas-trees:latest"

      - name: Restart Docker container on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME "docker stop texas-trees || true"
          ssh -i key.pem -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME "docker rm texas-trees || true"
          ssh -i key.pem -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME "docker run -d -p 80:5000 ghcr.io/almccutc/texas-trees:latest"
