name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}

      - name: Pull Docker image on EC2
        run: |
          ssh -o StrictHostKeyChecking=no $USER_NAME@$HOSTNAME "docker pull ghcr.io/almccutc/texas-trees:latest"

      - name: Restart Docker container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }} "docker stop texas-trees || true"
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }} "docker rm texas-trees || true"
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }} "docker run -d -p 80:5000 ghcr.io/almccutc/texas-trees:latest"
